// types and interfaces
import type { FetchProps } from './types'

const mock: FetchProps = [
  {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    name: 'Monalisa Octocat',
    company: 'GitHub',
    blog: 'https://github.blog',
    location: 'San Francisco',
    email: null,
    hireable: null,
    bio: 'Building open source projects and octocats.',
    twitter_username: null,
    public_repos: 2,
    public_gists: 1,
    followers: 20,
    following: 0,
    created_at: '2008-01-14T04:33:35Z',
    updated_at: '2008-01-14T04:33:35Z'
  },
  {
    login: 'torvalds',
    id: 102402,
    node_id: 'MDQ6VXNlcjEwMjQwMg==',
    avatar_url: 'https://avatars.githubusercontent.com/u/102402?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/torvalds',
    html_url: 'https://github.com/torvalds',
    followers_url: 'https://api.github.com/users/torvalds/followers',
    following_url: 'https://api.github.com/users/torvalds/following{/other_user}',
    gists_url: 'https://api.github.com/users/torvalds/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/torvalds/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/torvalds/subscriptions',
    organizations_url: 'https://api.github.com/users/torvalds/orgs',
    repos_url: 'https://api.github.com/users/torvalds/repos',
    events_url: 'https://api.github.com/users/torvalds/events{/privacy}',
    received_events_url: 'https://api.github.com/users/torvalds/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    name: 'Linus Torvalds',
    company: 'Linux Foundation',
    blog: '',
    location: 'Portland, OR',
    email: null,
    hireable: null,
    bio: 'Creator of Linux and Git',
    twitter_username: null,
    public_repos: 6,
    public_gists: 0,
    followers: 220000,
    following: 0,
    created_at: '2011-09-03T15:26:22Z',
    updated_at: '2026-01-01T00:00:00Z'
  }
]

export default mock
