// types and interfaces
import type { TUserMap } from 'models/Users/$/types'

export default new Map([
  [
    'ayrtonteshima',
    {
      id: 1896557,
      node_id: 'MDQ6VXNlcjE8OTY1NTc=',
      avatar_url: 'https://avatars.githubusercontent.com/u/1896557?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ayrtonteshima',
      html_url: 'https://github.com/ayrtonteshima',
      followers_url: 'https://api.github.com/users/ayrtonteshima/followers',
      following_url: 'https://api.github.com/users/ayrtonteshima/following{/other_user}',
      gists_url: 'https://api.github.com/users/ayrtonteshima/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ayrtonteshima/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ayrtonteshima/subscriptions',
      organizations_url: 'https://api.github.com/users/ayrtonteshima/orgs',
      repos_url: 'https://api.github.com/users/ayrtonteshima/repos',
      events_url: 'https://api.github.com/users/ayrtonteshima/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ayrtonteshima/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false,
      name: 'Ayrton Teshima',
      company: 'Content creator at Programador a Bordo',
      blog: 'https://programadorabordo.com.br',
      location: 'Piracicaba - SP',
      email: null,
      hireable: null,
      bio: 'Criador de conteúdo no canal Programador a Bordo. #javascript #jsraiz #programadorabordo',
      twitter_username: 'devabordo',
      public_repos: 39,
      public_gists: 3,
      followers: 269,
      following: 8,
      created_at: '2012-06-27T01:52:01Z',
      updated_at: '2026-07-23T01:27:41Z',
      accessedAt: 1785181390874
    }
  ],
  [
    'linuxmint',
    {
      id: 107184,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjEwNzE4NA==',
      avatar_url: 'https://avatars.githubusercontent.com/u/107184?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/linuxmint',
      html_url: 'https://github.com/linuxmint',
      followers_url: 'https://api.github.com/users/linuxmint/followers',
      following_url: 'https://api.github.com/users/linuxmint/following{/other_user}',
      gists_url: 'https://api.github.com/users/linuxmint/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/linuxmint/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/linuxmint/subscriptions',
      organizations_url: 'https://api.github.com/users/linuxmint/orgs',
      repos_url: 'https://api.github.com/users/linuxmint/repos',
      events_url: 'https://api.github.com/users/linuxmint/events{/privacy}',
      received_events_url: 'https://api.github.com/users/linuxmint/received_events',
      type: 'Organization',
      user_view_type: 'public',
      site_admin: false,
      name: 'Linux Mint',
      company: null,
      blog: 'https://linuxmint-developer-guide.readthedocs.io',
      location: null,
      email: null,
      hireable: null,
      bio: 'https://www.linuxmint.com',
      twitter_username: null,
      public_repos: 156,
      public_gists: 0,
      followers: 5368,
      following: 0,
      created_at: '2009-07-21T07:35:45Z',
      updated_at: '2022-11-25T12:15:21Z',
      accessedAt: 1785181540071
    }
  ],
  [
    'diego3g',
    {
      id: 2254731,
      node_id: 'MDQ6VXNlcjIyNTQ3MzE=',
      avatar_url: 'https://avatars.githubusercontent.com/u/2254731?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/diego3g',
      html_url: 'https://github.com/diego3g',
      followers_url: 'https://api.github.com/users/diego3g/followers',
      following_url: 'https://api.github.com/users/diego3g/following{/other_user}',
      gists_url: 'https://api.github.com/users/diego3g/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/diego3g/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/diego3g/subscriptions',
      organizations_url: 'https://api.github.com/users/diego3g/orgs',
      repos_url: 'https://api.github.com/users/diego3g/repos',
      events_url: 'https://api.github.com/users/diego3g/events{/privacy}',
      received_events_url: 'https://api.github.com/users/diego3g/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false,
      name: 'Diego Fernandes',
      company: null,
      blog: '',
      location: 'Brazil',
      email: null,
      hireable: null,
      bio: 'coding...',
      twitter_username: 'dieegosf',
      public_repos: 75,
      public_gists: 166,
      followers: 32689,
      following: 88,
      created_at: '2012-08-31T11:46:00Z',
      updated_at: '2026-06-08T14:14:32Z',
      accessedAt: 1785181380180
    }
  ],
  [
    'holasoycael',
    {
      id: 9421010,
      node_id: 'MDQ6VXNlcjk0MjEwMTA=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9421010?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/holasoycael',
      html_url: 'https://github.com/holasoycael',
      followers_url: 'https://api.github.com/users/holasoycael/followers',
      following_url: 'https://api.github.com/users/holasoycael/following{/other_user}',
      gists_url: 'https://api.github.com/users/holasoycael/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/holasoycael/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/holasoycael/subscriptions',
      organizations_url: 'https://api.github.com/users/holasoycael/orgs',
      repos_url: 'https://api.github.com/users/holasoycael/repos',
      events_url: 'https://api.github.com/users/holasoycael/events{/privacy}',
      received_events_url: 'https://api.github.com/users/holasoycael/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false,
      name: 'Natanael Lourenço',
      company: null,
      blog: '',
      location: 'São Paulo - Brasil',
      email: null,
      hireable: null,
      bio: 'Full Stack Developer 👨🏻💻',
      twitter_username: null,
      public_repos: 17,
      public_gists: 1,
      followers: 31,
      following: 6,
      created_at: '2014-10-27T18:13:46Z',
      updated_at: '2026-07-26T17:12:56Z',
      accessedAt: 1785181402029
    }
  ],
  [
    'dgobatista',
    {
      id: 26335096,
      node_id: 'MDQ6VXNlcjI2MzM1MDk2',
      avatar_url: 'https://avatars.githubusercontent.com/u/26335096?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/dgobatista',
      html_url: 'https://github.com/dgobatista',
      followers_url: 'https://api.github.com/users/dgobatista/followers',
      following_url: 'https://api.github.com/users/dgobatista/following{/other_user}',
      gists_url: 'https://api.github.com/users/dgobatista/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/dgobatista/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/dgobatista/subscriptions',
      organizations_url: 'https://api.github.com/users/dgobatista/orgs',
      repos_url: 'https://api.github.com/users/dgobatista/repos',
      events_url: 'https://api.github.com/users/dgobatista/events{/privacy}',
      received_events_url: 'https://api.github.com/users/dgobatista/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false,
      name: 'Diego Batista',
      company: 'Cda Gaming',
      blog: '',
      location: 'Salvador - Bahia',
      email: null,
      hireable: null,
      bio: 'Vitima de falsificação de software.',
      twitter_username: null,
      public_repos: 0,
      public_gists: 0,
      followers: 10,
      following: 15,
      created_at: '2017-03-10T21:24:13Z',
      updated_at: '2026-07-16T09:40:58Z',
      accessedAt: 1785181509030
    }
  ]
]) satisfies TUserMap
